//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int idProduit { get; set; }
        public string nomProduit { get; set; }
        public string descriptionProduit { get; set; }
        public decimal qteProduit { get; set; }
        public decimal puProduit { get; set; }
        public decimal qteSeuilProduit { get; set; }
        public Nullable<int> idCategorie { get; set; }
    }
}
